version: '3.9'

services:
  # traefik:
  #   image: "traefik:v3.2"
  #   command:
  #     - "--api.insecure=false"
  #     - "--api.dashboard=false"
  #     - "--providers.docker=true"
  #     - "--providers.docker.exposedbydefault=false"
  #     - "--entrypoints.web.address=:80"
  #     - "--entrypoints.websecure.address=:443"
  #     - "--entrypoints.websecure.http.tls=true"
  #     - "--entrypoints.websecure.http.tls.certResolver=myresolver"
  #     - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
  #     - "--certificatesresolvers.myresolver.acme.email=admin@apptest.local"
  #     - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
  #     - "--log.level=INFO"
  #   ports:
  #     - "443:443"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock:ro"
  #     - "./letsencrypt:/letsencrypt"
  #   networks:
  #     - temporal-network
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.api.rule=Host(`apptest.local`)"
  #     - "traefik.http.routers.api.service=api@internal"
  #     - "traefik.http.routers.api.entrypoints=websecure"
  #     - "traefik.http.routers.api.tls.certresolver=myresolver"

  postgresql:
    container_name: temporal-postgresql
    environment:
      POSTGRES_PASSWORD: temporal
      POSTGRES_USER: temporal
    image: postgres:latest
    ports:
      - 5432:5432
    networks:
      - temporal-network

  temporal:
    container_name: temporal
    depends_on:
      - postgresql
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
    image: temporalio/auto-setup:latest
    volumes:
      - ./dynamicconfig:/etc/temporal/config/dynamicconfig
    networks:
      - temporal-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grpc.rule=Host(`temporal.apptest.local`)"
      - "traefik.http.routers.grpc.entrypoints=websecure"
      - "traefik.http.routers.grpc.tls.certresolver=myresolver"
      - "traefik.http.services.grpc.loadbalancer.server.scheme=h2c"
      - "traefik.http.services.grpc.loadbalancer.server.port=7233"
  
  temporal-admin-tools:
    container_name: temporal-admin-tools
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    image: temporalio/admin-tools:latest
    stdin_open: true
    tty: true
    networks:
      - temporal-network

networks:
  temporal-network:
    driver: bridge
    name: temporal-network